### PR TITLE
#2432 Add deleted scores to admin score details page

### PR DESCRIPTION
**Pull request by shaunxp20**
This will allow admins to see deleted scores on the score details page.

#2432

### CODE REVIEW

**Comment by shaunxp20** [comment]
I tried writing a system spec for this, but I couldn't figure out how to get a submission viewable to an RA, giving up for now. 😭 Anywho, curious what your thoughts are on these changes, @stenington, and on a system spec; seems like there will be some extra time in this iteration so I can keep cranking on it. 🤔 ❓

**Comment by stenington** [comment]
Just seeing your question about a system spec, let me think about that.

**Comment by stenington** [comment]
RAs can see the score details page for submissions in their region only after the admin has turned "Scores & Certificates Accessible" on. I think some of our factories have traits like `:chicago` or `:los_angeles` so you can create users and teams in the same region to ensure an RA can see them. Does that get you what you need for testing?

**Comment by shaunxp20** [comment]
> RAs can see the score details page for submissions in their region only after the admin has turned "Scores & Certificates Accessible" on. I think some of our factories have traits like `:chicago` or `:los_angeles` so you can create users and teams in the same region to ensure an RA can see them. Does that get you what you need for testing?

Thank @stenington! Hmm, I thought that's what I was trying! Nonetheless, I'll try again w/ fresh eyes/mind, and see if I can make some more progress! 😁 👍 🌞

**Comment by shaunxp20** [comment]
@stenington This one is ready for another looksie when you get a moment.

* I added a system spec
* The only change I made to the production code since you last looked at it was adding some `div`s for the complete/incomplete quarter/semifinal score sections for the tests to us
* I didn't realize there's a similar feature spec for this, doh! 🤦‍♂ 
* So many in-and-outs of the score search/details page, I didn't know where to stop, seems like there are quite a few more scenarios to test, but at least this is a start 🤷‍♂ 😄

**Comment by stenington** [comment]
Wow, yeah the RA view of the "Scores" page is obnoxiously complex. I mean... I think these tests are great! I'd be happy with this as-is.

**Pull request merged**
