### PR TITLE
#2487 Add integration spec for content and settings page

### PR DESCRIPTION
**Pull request by stenington**
This drives the content and settings admin page and checks that the appropriate `SeasonToggles` are set.

I tried the given/when/then format as well, but it felt to me like it was harder to see the connection between UI and `SeasonToggles` without adding much clarity.

### CODE REVIEW

**Comment by shaunxp20** [comment]
I didn't see any specs for setting the judging round and how that turns on/off other settings. I think it would be good to test the more complicated scenarios. I'm fine w/ another ticket if we want to just get this one wrapped up. Thoughts?

**Comment by stenington** [comment]
I'll try to add those here, but I'll kick it over to another ticket if it becomes too much. Good catch!

**Comment by stenington** [comment]
@shaunxp20 Okay, this is ready for another look. I'm now testing that certain judging rounds:
* disable other toggles on the backend
* show alerts that things have been disabled, and
* uncheck and disable the actual checkboxes too

while other judging rounds don't do the above. The file has gotten pretty long, and I keep getting tempted to try to do more clever dynamic things, but I think the simple procedural style will ultimately be more comprehensible. What do you think?

**Comment by shaunxp20** [comment]
> @shaunxp20 Okay, this is ready for another look. I'm now testing that certain judging rounds:
> 
>     * disable other toggles on the backend
> 
>     * show alerts that things have been disabled, and
> 
>     * uncheck and disable the actual checkboxes too
> 
> 
> while other judging rounds don't do the above. The file has gotten pretty long, and I keep getting tempted to try to do more clever dynamic things, but I think the simple procedural style will ultimately be more comprehensible. What do you think?

I definitely prefer readability in tests, so doing w/o more clever dynamic things is fine w/ me!

**Pull request merged**
