### PR TITLE
Change the certificate type name from completion to quarterfinalist

### PR DESCRIPTION
**Pull request by devkonrad**
This PR correct the name of the certificate name from "Completion" to "Quarterfinalist".

_Note: As we use the same completion's ID, it will affectt the name of the previous certificates too. If we dont want that, i believe that will be necessary create a new ID for this one and maintain the name "completion" for the old certificates._

Ref.: #3527

### CODE REVIEW

**Review by viviancan — APPROVED** [review]
Tried this locally! Was able to generate "quarterfinalist" certificate and view the quarterfinalist certificate. I also ran the generate certificate rake task locally and the appropriate certificates were generated. Thanks for taking care of this one, Alex 🚀 👍 

Shaun may want to take a look at this as well before merging! We can touch base in the standup today :)

**Comment by devkonrad** [comment]
> Tried this locally! Was able to generate "quarterfinalist" certificate and view the quarterfinalist certificate. I also ran the generate certificate rake task locally and the appropriate certificates were generated. Thanks for taking care of this one, Alex rocket +1
> 
> Shaun may want to take a look at this as well before merging! We can touch base in the standup today :)

Thanks for the review, @viviancan ! :)

**Review by shaunxp20 — APPROVED** [review]
Awesome, looks good to me! Thanks for taking care of this one, Alex! 👍 🙌 🥳 :shipit:

**Comment by devkonrad** [comment]
> Awesome, looks good to me! Thanks for taking care of this one, Alex! +1 raised_hands partying_face :shipit:

Thanks for the review, @shaunxp20 ! :) Going to merge it!

**Pull request merged**
