### PR TITLE
Clean up language throughout platform

### PR DESCRIPTION
**Pull request by rsgonzal**
- Update step one screen language

### CODE REVIEW

**Comment by rsgonzal** [comment]
ran into you! @shaunxp20

**Comment by shaunxp20** [comment]
> ran into you! @shaunxp20

Just updated it, should be good now! 😀 🌞

**Comment by rsgonzal** [comment]
thank yoUu!

**Comment by rsgonzal** [comment]
None of the links have headers anymore, removed the 'help us improve' that pops up when survey available
Screen Shot 2021-12-02 at 4 13 58 PM

**Pull request merged**
