### PR TITLE
#1994 Expand Scores & Feedback section to fit the entire view on mentor dashboard

### PR DESCRIPTION
**Pull request by adrichey**
Addresses #1994.

### CODE REVIEW

**Comment by adrichey** [comment]
@RRios00 I will be out of the office from tomorrow March 7th, through the 11th. So if you need assistance with this review, or need to hand it off during that time, please reach out to Mike @stenington for assistance. This isn't a super complex PR, and it isn't going to break anything if it doesn't get into QA right away, so take your time, but do reach out if you need to. Thanks!

**Comment by RRios00** [comment]
Thanks @adrichey! I'll take a look at this today. 👍

**Comment by adrichey** [comment]
@RRios00 do you have time to look at this this week? If not, no worries, I can transfer this to Mike. I would like to get this into production before too long since this is needed for the judging sprint. Thanks!

**Comment by adrichey** [comment]
@RRios00 I am going to transfer this PR over to Mike to review. I want to get it into this release as it missed the last one since it is a nice improvement to the UI for scores. Thanks!

**Pull request merged**
