### PR TITLE
Rebrands team search for students

### PR DESCRIPTION
**Pull request by devkonrad**
Rebrands team search for students
Captura de tela de 2022-07-12 16-45-34

Captura de tela de 2022-07-12 16-45-56

_NOTE: As the "Anywhere"  and "Near me" filter are excludent, i implemented a radio_button instead of a checkbox._

Changes:
modified: app/views/searches/rebrand/_location_options.en.html.erb
modified: app/views/team_searches/_filter_options.en.html.erb
modified: app/views/team_searches/_new.html.erb
modified: app/views/team_searches/_result.html.erb
modified: app/views/team_searches/_search.html.erb
modified: app/views/team_searches/rebrand/_filter_options.en.html.erb
modified: app/views/team_searches/rebrand/_result.html.erb
modified: app/views/team_searches/rebrand/_search.html.erb
modified: spec/features/student/find_a_team_spec.rb

Refs: https://github.com/Iridescent-CM/technovation-app/issues/3203

### CODE REVIEW

**Comment by devkonrad** [comment]
> After a functionality review, the following changes are needed:
> 
> * [x]  Search defaults to "near me" so that radio button should be selected by default
> * [ ]  Display default photo or a blank tile the size of the image space if the image uploaded by the team is broken
> * [x]  Add green color and new styling to radio buttons and check boxes in search bar (check to see if these elements already exist)
> * [x]  Add new styling to pagination (check to see if these elements already exist)
> * [ ]  Remove the highlighting on the Division label on the team card and left align that text below the location

The itens about passed to the scope of the Rebrand Card Component [#3519](https://github.com/Iridescent-CM/technovation-app/pull/3519). This PR need to be blocked for publish until that be approved and merged.

**Comment by devkonrad** [comment]
> Rebrands team search for students
> 
> Captura de tela de 2022-06-22 07-10-53
> 
> _NOTE: As the "Anywhere" and "Near me" filter are excludent, i implemented a radio_button instead of a checkbox._
> 
> Changes: modified: app/views/searches/rebrand/_location_options.en.html.erb modified: app/views/team_searches/_filter_options.en.html.erb modified: app/views/team_searches/_new.html.erb modified: app/views/team_searches/_result.html.erb modified: app/views/team_searches/_search.html.erb modified: app/views/team_searches/rebrand/_filter_options.en.html.erb modified: app/views/team_searches/rebrand/_result.html.erb modified: app/views/team_searches/rebrand/_search.html.erb modified: spec/features/student/find_a_team_spec.rb
> 
> Refs: #3203

This PR is not blocked anymore, once the dependence https://github.com/Iridescent-CM/technovation-app/pull/3519 was merged into QA.

**Comment by viviancan** [comment]
I think this one can be closed since this was merged with #3482

**Comment by devkonrad** [comment]
> I think this one can be closed since this was merged with #3482

Yes, its right. I will close! Thanks @viviancan !

**Pull request closed without merging**
