### PR TITLE
Remove mentor age any place it is publicly visible

### PR DESCRIPTION
**Pull request by devkonrad**
Remove mentor age any place it is publicly visible

Changes:
modified: app/views/mentor/profiles/_basic.en.html.erb

Refs: https://github.com/Iridescent-CM/technovation-app/issues/3219

### CODE REVIEW

**Comment by devkonrad** [comment]
> Remove mentor age any place it is publicly visible
> 
> Changes: modified: app/views/mentor/profiles/_basic.en.html.erb
> 
> Refs: #3219

I tried to get any other place to change but i didn't found.

**Review by viviancan — COMMENTED** [review]
Looks good to me! I did a brief check as well and could not find mentor age specifically. I did see judge and student age!

**Comment by shaunxp20** [comment]
Simple enough! Looks good to me too! 🥳  🎊 🎈

Before merging this one in, let's meet up and iron out the merging process! Let me know what works for you! 😄

**Review by shaunxp20 — APPROVED** [review]

**Comment by devkonrad** [comment]
> Looks good to me! I did a brief check as well and could not find mentor age specifically. I did see judge and student age! Thanks for taking care of this Alex +1

Thak you, Vivian! :)

**Comment by devkonrad** [comment]
> Simple enough! Looks good to me too! partying_face confetti_ball balloon
> 
> Before merging this one in, let's meet up and iron out the merging process! Let me know what works for you! smile

Thank you, Shaun! I'll merge it tomorrow, I call you to follow the process! :)

**Pull request merged**
