### PR TITLE
#2470: updating certificate templates

### PR DESCRIPTION
**Pull request by stenington**
This PR gets us updated certificate templates and field logic for 2020. The semifinalist certificate update is still pending.

### CODE REVIEW

**Comment by stenington** [comment]
@shaunxp20 Locally, I get `PdfForms::PdftkError in Admin::CertificatesController#create` if I try to generate these certificates, but I want to try them on staging as-is to see if staging handles them okay. If not, I have a workaround to fix the files locally which I assume would also fix them on the server.

How do you feel about merging this branch into `qa` vs. me putting this branch on QA without a merge?

**Comment by shaunxp20** [comment]
> How do you feel about merging this branch into `qa` vs. me putting this branch on QA without a merge?

Yup, feel free to put this branch directly on QA (or merge or whatever)! :thumbsup: I just merged my outstanding PR (#2477) so QA is yours! 😄

**Comment by shaunxp20** [comment]
Btw, let me know when you're done w/ QA. For some reason the QA deploy job/build didn't get kicked off for #2477, so I still need to get that one on QA, doh! #no-rush 😊 🤔 😄

**Comment by stenington** [comment]
@shaunxp20 Ok, go ahead with whatever you need. I'm just merging this, and if the certificates blow up I'll put up another PR to fix it.

**Comment by shaunxp20** [comment]
> @shaunxp20 Ok, go ahead with whatever you need. I'm just merging this, and if the certificates blow up I'll put up another PR to fix it.

Looks like your latest merge deployed the Poppins font (#2477) with it, so we're good! 👍

**Pull request merged**
