### PR TITLE
#1946 Ending virtual qfs before live qfs

### PR DESCRIPTION
**Pull request by stenington**
Opening this for discussion.

This PR introduces a `judging_enabled_for?` companion to `judging_enabled?` that takes into account both the quarterfinals setting in the admin **and** the current date compared to the appropriate quarterfinal ending date (virtual or live). 

I wouldn't call it a totally "clean" solution for the same reasons discussed elsewhere, but until we iron out an overall approach to `SeasonToggles` vs. dates it may be enough to get us through this season?

The way this is intended to work is that we'd turn on quarterfinals at the quarterfinal start date, then both virtual and live judging will be available until the virtual quarterfinals end date. At that point virtual judges will no longer see scoring controls on their dashboards, but live judges still will. Then when live judging ends, we'd turn off quarterfinals in the admin. Once we're ready for semifinals, we should be able to turn that on through the admin and all judges should see the same virtual judging controls. If we needed to extend virtual judging, we'd do that by changing the date.

One thing I could do is screenshot out that whole flow and share that with the program team for a 👍 if we're not ready for this to land on QA.

### CODE REVIEW

**Comment by adrichey** [comment]
@stenington I think this sounds like a good approach and the logic makes sense to me. I think having QA buy-in might be a good way to go on this one since it directly impacts the way they handle their season. That way they can properly put out any fires that come up. We will also want to put the helper text somewhere that they had outlined on #1946 so that people know when virtual judging will end if it is not already out there somewhere. I apologize if it is and I didn't see it, I am kind of all over the place this afternoon so I only focused on the code in this PR.

**Comment by stenington** [comment]
Okay, so let me put together a series of screenshots next week that show the basic flow through the quarterfinals for live and virtual judges, and I'll post those in #1946 for approval. If changes get requested (e.g. better messaging of the deadlines) I'll add that to this PR.

**Comment by stenington** [comment]
Just noting here: I haven't put together screenshots because I think the ongoing exploratory QA will give us the feedback needed here. At least I hope so.

**Comment by stenington** [comment]
Even though we're now talking about virtual and live QFs ending on the same date, I think we should consider accepting this PR. I think it helps clarify some internal logic around judging, and enforces the cutoff more thoroughly.

**Comment by stenington** [comment]
Okay @adrichey this is ready for review

**Comment by stenington** [comment]
I'm closing this PR out, and will issue a new one if needed.

**Pull request closed without merging**
