### PR TITLE
#2694 Update Mentor Skills & Interests

### PR DESCRIPTION
**Pull request by shaunxp20**
Renaming Mentor Expertises to Skills & Interests; and removing/adding some, and ordering them.

### CODE REVIEW

**Comment by stenington** [comment]
Can you fix [the bootstrap task](https://github.com/Iridescent-CM/technovation-app/blob/qa/lib/tasks/bootstrap.rake) to set up the correct ones as well?

**Comment by shaunxp20** [comment]
> Can you fix [the bootstrap task](https://github.com/Iridescent-CM/technovation-app/blob/qa/lib/tasks/bootstrap.rake) to set up the correct ones as well?

Good catch, I just pushed up a commit to fix these as well. 👍

**Review by stenington — CHANGES_REQUESTED** [review]
If I drop my database and use `bin/setup` to rebuild, I get the right expertise options but without any order set on them.

**Comment by shaunxp20** [comment]
> If I drop my database and use `bin/setup` to rebuild, I get the right expertise options but without any order set on them.

I think this one is ready for another round, I removed the bootstrap task, so now all the Skills & Interests/Expertises will get created via migrations. I think it's right, I didn't drop my database to verify though.

**Comment by stenington** [comment]
Well, it turns out this doesn't work. It looks like `bin/setup` runs `rails db:setup`, which in turn creates the database from `db/schema.rb` or `db/structure.sql`, but does **not** run all migrations. I didn't realize that's how `bin/setup` worked.

Digging a little deeper, [this article](https://codingitwrong.com/2016/07/29/how-to-seed-and-migrate-rails-data.html) (which in turn references [this Thoughtbot article](https://thoughtbot.com/blog/data-migrations-in-rails)) make a case for keeping data changes out of db migrations, and I see their point in the long run. 

I think using `db/seeds.rb` to set up development and test databases should work, and then whether you want to keep the production expertise set up in a migration or not is up to you for now. Going forward maybe we shouldn't rely on that pattern but if this needs to get out the door, I don't think there's anything wrong with doing it that way in the short term.

**Comment by shaunxp20** [comment]
Good digging on this one! A lot of that makes sense to me.

Incorporating some of the ideas in those articles, and somewhat thinking out loud here for my next steps:
* only add one migration to add an `order` column (changing schema only)
* update (remove/add/order) expertises in a new rake task (which we'd need to run manually on QA/prod, and afterwards I can add a PR to remove this)
* update `db/seeds.rb` with the default expertises/ordering

Thoughts on this? 🤔

**Comment by stenington** [comment]
I think that sounds great!

**Comment by shaunxp20** [comment]
>* only add one migration to add an `order` column (changing schema only) 
>* update (remove/add/order) expertises in a new rake task (which we'd need to run manually on QA/prod, and afterwards I can add a PR to remove this)
>* update `db/seeds.rb` with the default expertises/ordering

Okay, I made these changes, it's ready for another pass when you get a moment. Also, I tested this w/ a QA database (by migrating, and running the new rake task), and also w/ a new database (via db:drop db:setup), and both are working as expected for me.

**Comment by stenington** [comment]
Cool, I can confirm this sets up my dev expertises table correctly.

**Review by stenington — APPROVED** [review]

**Pull request merged**
