### PR TITLE
#2492 Add feature specs for Regional Pitch Events

### PR DESCRIPTION
**Pull request by shaunxp20**
This will add feature specs for these scenarios:

RPEs:
 * creating/viewing an event
 * editing an event
 * deleting an event

Teams:
 * a team can be added to an event
 * a team can be removed from an event
 * a team cannot be added if it goes over the event capacity

Judges:
 * a judge can be added to an event
 * a judge can be removed from an event

### CODE REVIEW

**Comment by shaunxp20** [comment]
I think this is finally ready for a looksie, the build is passing more consistently now (five times in a row currently). I think I mentioned before about how specific/brittle the selectors are, and definitely not the best tests I have written, but it accomplishes the objective of wrapping some of the RPE stuff in tests. :-/ ¯\_(ツ)_/¯

**Comment by stenington** [comment]
I got this failure on 3/3 runs locally: 

```
Failures:

  1) Regional Pitch Events successfully creates a new event
     Failure/Error: expect(find_field("Date").value).to be_present
       expected `"".present?` to return true, got false
     
     [Screenshot]: tmp/screenshots/failures_r_spec_example_groups_regional_pitch_events_successfully_creates_a_new_event_182.png

     
     # ./spec/system/chapter_ambassador/regional_pitch_events_spec.rb:14:in `block (2 levels) in <main>'

```

The screenshot is this:

failures_r_spec_example_groups_regional_pitch_events_successfully_creates_a_new_event_182

Any thoughts on what might be going on?

**Comment by stenington** [comment]
Oh, I think maybe the test is trying to pick a date that's disabled based on my local environment maybe?

**Comment by stenington** [comment]
The latest commit doesn't fix this issue for me. I think it's because on the js side, environment config isn't read in dynamically, it's essentially compiled in by webpack.

**Comment by shaunxp20** [comment]
When you get a chance, can you see if this latest push fixed the issue you were seeing? 🤞

**Comment by stenington** [comment]
@shaunxp20 Yep, they passed!

**Pull request merged**
